language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: nySdhyaSci1fZKx8PWDt1UZtrm2OAkiZiR/+w/n3gq0X+OnsMOnyWbn7cuEUd3VvM8pmSqmLG/hLsNBzX0rHruW/UrSTYmfVkzzjHNE4sAj6XZTd3MjU/WwwOpDdWvN+s0K4hwy+47FiR59Y0kDKv5AIBAWOd5nfQV+1IXnHeQs=
  app: moz-corsica
  on:
    repo: mozilla/moz-corsica
